const sample=[
 {timestamp:"10:15:30",latitude:35.72196,longitude:140.05772,altitude_m:31.4,satellites:8,fix:1},
 {timestamp:"10:15:42",latitude:35.72219,longitude:140.05808,altitude_m:32.1,satellites:9,fix:1},
 {timestamp:"10:15:54",latitude:35.72247,longitude:140.05852,altitude_m:32.7,satellites:9,fix:1},
 {timestamp:"10:16:06",latitude:35.72273,longitude:140.05895,altitude_m:33.6,satellites:10,fix:1},
 {timestamp:"10:16:18",latitude:35.72298,longitude:140.05942,altitude_m:34.2,satellites:10,fix:1},
 {timestamp:"10:16:30",latitude:35.72324,longitude:140.05977,altitude_m:34.9,satellites:9,fix:1},
 {timestamp:"10:16:42",latitude:35.72349,longitude:140.06014,altitude_m:35.3,satellites:9,fix:1}
];
let points=[...sample],selected=points.at(-1),port=null,reader=null,jsonTimer=null;
const $=id=>document.getElementById(id);
const map=L.map("map",{zoomControl:false,minZoom:16,maxZoom:19}).setView([35.7227,140.0593],17);L.control.zoom({position:"bottomright"}).addTo(map);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);let layer=L.layerGroup().addTo(map);
function coordinate(value,dir){if(!value||!dir)return null;const n=dir==="N"||dir==="S"?2:3,d=Number(value.slice(0,n)),m=Number(value.slice(n));if(!Number.isFinite(d)||!Number.isFinite(m))return null;const x=d+m/60;return dir==="S"||dir==="W"?-x:x}
function parseNmea(line){const f=line.trim().split(","),type=(f[0]||"").replace(/^\$/i,"").split("*")[0];if(type.endsWith("GGA")){const lat=coordinate(f[2],f[3]),lon=coordinate(f[4],f[5]);if(lat===null||lon===null||Number(f[6])===0)return null;return {timestamp:f[1]||"--:--:--",latitude:lat,longitude:lon,altitude_m:Number(f[9])||0,satellites:Number(f[7])||0,fix:1}}if(type.endsWith("RMC")&&f[2]==="A"){const lat=coordinate(f[3],f[4]),lon=coordinate(f[5],f[6]);if(lat===null||lon===null)return null;return {timestamp:f[1]||"--:--:--",latitude:lat,longitude:lon,altitude_m:0,satellites:0,fix:1}}return null}
function render(){layer.clearLayers();const loc=points.map(p=>[p.latitude,p.longitude]);if(loc.length>1)L.polyline(loc,{color:"#0b6e69",weight:4,opacity:.9}).addTo(layer);points.forEach((p,i)=>{const last=i===points.length-1,m=L.circleMarker([p.latitude,p.longitude],{radius:last?8:5,color:last?"#f26b38":"#0b6e69",fillColor:last?"#f26b38":"#8bd4c7",fillOpacity:1,weight:2}).addTo(layer);m.bindPopup(`<strong>${last?"最新位置":`GPS点 ${i+1}`}</strong><br>${p.timestamp}<br>高度 ${p.altitude_m.toFixed(1)} m<br>衛星数 ${p.satellites}`);m.on("click",()=>{selected=p;renderDetails()})});renderDetails();$("count").textContent=points.length;$("mapCount").textContent=`${points.length}点を表示中`;$("maxAlt").textContent=Math.max(...points.map(p=>p.altitude_m)).toFixed(1);const bars=$("bars");bars.innerHTML="";const max=Math.max(...points.map(p=>p.altitude_m),1);points.forEach((p,i)=>{const w=document.createElement("div");w.className="bar-wrap";w.innerHTML=`<div class="bar" style="height:${Math.max(14,p.altitude_m/max*100)}%"></div><span>${i+1}</span>`;bars.appendChild(w)})}
function renderDetails(){if(!selected)return;$("selectedTime").textContent=selected.timestamp;$("time").textContent=selected.timestamp;$("lat").textContent=selected.latitude.toFixed(6);$("lon").textContent=selected.longitude.toFixed(6);$("alt").textContent=`${selected.altitude_m.toFixed(1)} m`;$("sats").textContent=selected.satellites;$("selectedSats").textContent=selected.satellites;$("fix").textContent=selected.fix?"Fix取得中":"Fix待機中";$("fix").style.color=selected.fix?"#0b6e69":"#f26b38"}
function addPoint(p){points=[...points.slice(-199),p];selected=p;$("source").textContent="XBee / Web Serial";$("updated").textContent=`XBee受信 ${p.timestamp}`;$("status").className="status live";$("status").innerHTML="<i></i>XBee LIVE";render()}
async function connect(){if(!("serial" in navigator)){ $("updated").textContent="Chrome / Edgeで開いてください";return}try{port=await navigator.serial.requestPort();await port.open({baudRate:9600});reader=port.readable.getReader();$("connect").textContent="XBee切断";let buf="";const decoder=new TextDecoder();while(true){const r=await reader.read();if(r.done)break;buf+=decoder.decode(r.value,{stream:true});const lines=buf.split(/\r?\n/);buf=lines.pop()||"";lines.forEach(line=>{const p=parseNmea(line);if(p)addPoint(p)})}}catch(e){$("updated").textContent=e.message||"接続できませんでした"}finally{if(port){await port.close().catch(()=>{});port=null;reader=null;$("connect").textContent="XBeeに接続"}}}
$("connect").onclick=async()=>{if(port){await reader?.cancel();return}await connect()};$("jsonLive").onclick=()=>{if(jsonTimer){clearInterval(jsonTimer);jsonTimer=null;$("jsonLive").textContent="JSON更新";return}const load=async()=>{try{const r=await fetch("data/latest.json",{cache:"no-store"});if(r.ok){const d=await r.json();if(Array.isArray(d)&&d.length){points=d;selected=d.at(-1);$("source").textContent="latest.json";$("updated").textContent=`最終受信 ${selected.timestamp}`;render()}}}catch{}};load();jsonTimer=setInterval(load,2000);$("jsonLive").textContent="JSON停止"};$("download").onclick=()=>{const csv=["timestamp,latitude,longitude,altitude_m,satellites,fix",...points.map(p=>Object.values(p).join(","))].join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="hepta-gps-log.csv";a.click()};render();
